backend:
    name: github
    repo: itsbritt/itsbritt.com

media_folder: static/assets
public_folder: /assets

collections:
    - label: 'Pages'
      name: 'pages'
      files:
          - label: 'Home Page'
            name: 'home'
            file: 'content/home.md'
            fields:
                - { label: Title, name: title, widget: string }
                - { label: Intro text, name: intro, widget: text }
          - label: 'Resume Page'
            name: 'resume'
            file: 'content/resume.md'
            fields:
                - { label: Header, name: header, widget: string }
    - label: 'Jobs'
      name: 'jobs'
      folder: 'content/jobs'
      create: true
      identifier_field: companyName
      fields:
          - { label: Company Name, name: companyName, widget: string }
          - { label: Company URL, name: companyUrl, widget: string }
          - { label: Start Date, name: startDate, widget: datetime, date_format: 'MM-YY' }
          - { label: End Date, name: endDate, widget: datetime, date_format: 'MM-YY', required: false }
          - { label: Role, name: role, widget: string }
          - { label: Summary, name: summary, widget: markdown }
          - { label: Skills, name: skills, widget: list }
