backend:
    name: github
    repo: itsbritt/itsbritt.com

media_folder: static/assets
public_folder: /assets

collections:
    - label: 'Page'
      name: 'page'
      files:
          - label: 'Home Page'
            name: 'home'
            file: 'content/home.md'
            fields:
                - { label: Title, name: title, widget: string }
                - { label: Intro text, name: intro, widget: text }
          - label: 'Resume Page'
            name: 'resume'
            file: 'content/resume.md'
            fields:
                - { label: Header, name: header, widget: string }
    - label: 'Job'
      name: 'job'
      folder: 'content/jobs'
      create: true
      identifier_field: companyName
      fields:
          - { label: Company Name, name: companyName, widget: string }
          - { label: Company URL, name: companyUrl, widget: string }
          - { label: Start Date, name: startDate, widget: datetime, date_format: 'MM-YY' }
          - { label: End Date, name: endDate, widget: datetime, date_format: 'MM-YY', required: false }
          - { label: Role, name: role, widget: string }
          - { label: Summary, name: summary, widget: markdown }
          - { label: Skills, name: skills, widget: list }
    - label: 'Blog Post'
      name: 'blog'
      folder: 'content/digital_garden'
      create: true # Allow users to create new documents in this collection
      slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
      identifier_field: title
      fields: # The fields for each document, usually in front matter
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime', date_format: 'MM-DD-YY' }
          - { label: 'Featured Image', name: 'thumbnail', widget: 'image', required: false }
          - { label: 'Body', name: 'body', widget: 'markdown' }

slug:
    encoding: 'ascii'
    clean_accents: true
    sanitize_replacement: '_'
